### ISSUE TITLE
Import Error in Vite

### ISSUE THREAD

**Issue by OofYeetMcGee** [harrydehix/simple-units#11]
Hello,

I'm trying to use simple-units in my project. Here is the stack trace:

12:41:46 PM [vite] Error when evaluating SSR module /src/routes/report/+page.server.ts: failed to import "simple-units"
|- Error: Inside the flexible unit's format a '%' must be followed by a number indicating the variable's index!
    at FlexibleUnit.fillFormat (file:///home/user/git-repos/project/node_modules/simple-units/dist/FlexibleUnit.js:169:27)
    at FlexibleUnit.generateUnitFormat (file:///home/user/git-repos/project/node_modules/simple-units/dist/FlexibleUnit.js:155:39)
    at FlexibleUnit.create (file:///home/user/git-repos/project/node_modules/simple-units/dist/FlexibleUnit.js:110:36)
    at new FlexibleUnit (file:///home/user/git-repos/project/node_modules/simple-units/dist/FlexibleUnit.js:101:28)
    at file:///home/user/git-repos/project/node_modules/simple-units/dist/units/groups/mass.js:9:17
    at ModuleJob.run (node:internal/modules/esm/module_job:262:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:483:26)
    at async nodeImport (file:///home/user/git-repos/project/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:52999:15)
    at async ssrImport (file:///home/user/git-repos/project/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:52857:16)
    at async eval (/home/user/git-repos/project/src/routes/report/+page.server.ts:3:44)
    

I import the lib like this:
import units from "simple-units";

and the only line I try to use it is this:
const units_per = units.from(1, "gallons").to("ounces")

**Comment by harrydehix** [comment]
This has been fixed in `v1.1.5`.
